"""Application-wide constants (BRD defaults; some overridden by system config)."""

DEFAULT_MAX_WEEKLY_HOURS = 40
DEFAULT_SCHEDULER_INTERVAL_HOURS = 4
MIN_PASSWORD_LENGTH = 8
MAX_UTILISATION_PERCENT = 100
MIN_SCHEDULER_INTERVAL_HOURS = 1
MAX_SCHEDULER_INTERVAL_HOURS = 168
MIN_MAX_WEEKLY_HOURS = 1
MAX_MAX_WEEKLY_HOURS = 168
LLM_API_KEY_MASK = "*" * 28
